- name: Install & configure Wikitransbot
  hosts: onpre
  remote_user: supermeepboy
  vars:
    bot_name: wikitransbot
    remote_wikitransbot_folder: /home/supermeepboy/wikitransbot
    config_path: "{{ remote_wikitransbot_folder }}/config.json"

  tasks:
    - name: Set twitter_api_key
      replace:
        path: "{{ config_path }}"
        regexp: "twitter_api_key_placeholder"
        replace: "{{ twitter_api_key }}"
      become: true

    - name: Set twitter_api_key_secret
      replace:
        path: "{{ config_path }}"
        regexp: "twitter_api_key_secret_placeholder"
        replace: "{{ twitter_api_key_secret }}"
      become: true

    - name: Set twitter_access_token
      replace:
        path: "{{ config_path }}"
        regexp: "twitter_access_token_placeholder"
        replace: "{{ twitter_access_token }}"
      become: true

    - name: Set twitter_access_token_secret
      replace:
        path: "{{ config_path }}"
        regexp: "twitter_access_token_secret_placeholder"
        replace: "{{ twitter_access_token_secret }}"
      become: true

    - name: Set twitter_bearer_token
      replace:
        path: "{{ config_path }}"
        regexp: "twitter_bearer_token_placeholder"
        replace: "{{ twitter_bearer_token }}"
      become: true

    - name: Set user_id
      replace:
        path: "{{ config_path }}"
        regexp: "user_id_placeholder"
        replace: "{{ user_id }}"
      become: true

    - name: Set since_id file path
      replace:
        path: "{{ config_path }}"
        regexp: "last_id_file_placeholder"
        replace: "{{ last_id_file }}"
      become: true

    - name: Set logfile path
      replace:
        path: "{{ config_path }}"
        regexp: "logfile_path_placeholder"
        replace: "{{ logfile_path }}"
      become: true

    - name: Install pip
      apt:
        name: pip
        state: present
      become: true

    - name: Install Docker SDK for Python
      pip:
        name: docker

    - name: Build docker image
      docker_image:
        name: "{{ bot_name }}"
        build:
          path: "{{ remote_wikitransbot_folder }}"
        source: build

    - name: Run {{ bot_name }} docker container
      docker_container:
        name: "{{ bot_name }}"
        image: "{{ bot_name }}"
        volumes: "wikitransbot_data:/shared/data"
        state: started
        detach: true
