---
- hosts: onpre
  # remote_user: ubuntu
  remote_user: supermeepboy
  tasks:
    - name: Setup architecture
      include_tasks: "setup_architecture.yaml"
      vars:
        bot_name: wikitransbot

- hosts: onpre_become
  remote_user: supermeepboy
  tasks:
  - name: Install Docker
    import_tasks: "install_docker.yaml"
    become: true
  handlers:
  - name: Restart docker
    service: 
      name: docker 
      state: restarted
...
