---
- name: Create {{ bot_name }} directory
  file:
    path: /home/supermeepboy/{{ bot_name }}/{{ bot_name }}
    state: directory

- name: Copy {{ bot_name }} code
  copy:
    src: "{{ wikitransbot_folder }}/wikitransbot"
    dest: /home/supermeepboy/{{ bot_name }}/

- name: Copy {{ bot_name }} requirements.txt
  copy:
    src: "{{ wikitransbot_folder }}/requirements.txt"
    dest: /home/supermeepboy/{{ bot_name }}

- name: Copy {{ bot_name }} pyproject.toml
  copy:
    src: "{{ wikitransbot_folder }}/pyproject.toml"
    dest: /home/supermeepboy/{{ bot_name }}

- name: Copy {{ bot_name }} config_template.json
  copy:
    src: "{{ wikitransbot_folder }}/config_template.json"
    dest: /home/supermeepboy/{{ bot_name }}/config.json
  become: true
    
- name: Copy {{ bot_name }} Dockerfile
  copy:
    src: "{{ wikitransbot_folder }}/Dockerfile"
    dest: /home/supermeepboy/{{ bot_name }}

- name: Copy {{ bot_name }} since_id
  copy:
    src: "{{ wikitransbot_folder }}/since_id.txt"
    dest: /home/supermeepboy/{{ bot_name }}
...

