name: CI

on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check code quality
      run: |
        pip install flake8
        flake8
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run pytest
      run: |
        pip install -r requirements.txt
        pytest tests
